apiVersion: v1
kind: ConfigMap
metadata:
  name: quickbite-config
data:
  NODE_ENV: production
  APP_NAME: QuickBite
  KAFKA_BROKER: kafka-service:9092
  KAFKA_CLIENT_ID: quickbite-backend
  KAFKA_GROUP_ID: quickbite-consumers
  REDIS_URL: redis://redis-service:6379
  PORT_API_GATEWAY: "3000"
  PORT_USER_SERVICE: "3001"
  PORT_AUTH_SERVICE: "3002"
  PORT_MERCHANT_SERVICE: "3003"
  PORT_CATALOG_SERVICE: "3004"
  PORT_CART_SERVICE: "3005"
  PORT_ORDER_SERVICE: "3006"
  PORT_PAYMENT_SERVICE: "3007"
  PORT_DELIVERY_SERVICE: "3008"
  PORT_TRACKING_SERVICE: "3009"
  PORT_NOTIFICATION_SERVICE: "3010"
  PORT_SEARCH_SERVICE: "3011"
  PORT_LOYALTY_SERVICE: "3012"
  PORT_WALLET_SERVICE: "3013"
  PORT_SUBSCRIPTION_SERVICE: "3014"
  PORT_INVENTORY_SERVICE: "3015"
  PORT_ANALYTICS_SERVICE: "3016"
  PORT_ADMIN_SERVICE: "3017"
  PORT_CMS_SERVICE: "3018"
  PORT_REVIEW_SERVICE: "3019"
  PORT_GROUP_ORDER_SERVICE: "3020"
  PORT_SUPPORT_SERVICE: "3021"
