apiVersion: apps/v1
kind: Deployment
metadata:
  name: group-order-service
  labels:
    app: group-order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: group-order-service
  template:
    metadata:
      labels:
        app: group-order-service
    spec:
      containers:
        - name: group-order-service
          image: quickbite/group-order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3020
          envFrom:
            - secretRef:
                name: quickbite-secrets
            - configMapRef:
                name: quickbite-config
          env:
            - name: PORT_GROUP_ORDER_SERVICE
              value: "3020"
          readinessProbe:
            httpGet:
              path: /health
              port: 3020
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3020
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: group-order-service
spec:
  selector:
    app: group-order-service
  ports:
    - protocol: TCP
      port: 3020
      targetPort: 3020
  type: ClusterIP
