apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - user-service.yaml
  - auth-service.yaml
  - merchant-service.yaml
  - catalog-service.yaml
  - cart-service.yaml
  - order-service.yaml
  - payment-service.yaml
  - delivery-service.yaml
  - tracking-service.yaml
  - notification-service.yaml
  - search-service.yaml
  - loyalty-service.yaml
  - wallet-service.yaml
  - subscription-service.yaml
  - inventory-service.yaml
  - analytics-service.yaml
  - admin-service.yaml
  - cms-service.yaml
  - review-service.yaml
  - group-order-service.yaml
  - support-service.yaml
  - secrets.yaml
  - configmap.yaml
